const phones = [
  // NEW PHONES
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    storage: "256 ГБ",
    color: "Натуральный титан",
    price: 649000,
    condition: "new",
    badge: "Хит продаж",
    emoji: "📱",
    specs: ["A17 Pro", "48 МП камера", "USB-C", "Action Button"],
  },
  {
    id: 2,
    name: "iPhone 15",
    brand: "Apple",
    storage: "128 ГБ",
    color: "Чёрный",
    price: 399000,
    condition: "new",
    badge: null,
    emoji: "📱",
    specs: ["A16 Bionic", "Dynamic Island", "USB-C", "48 МП"],
  },
  {
    id: 3,
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    storage: "256 ГБ",
    color: "Серый",
    price: 599000,
    condition: "new",
    badge: "Новинка",
    emoji: "📱",
    specs: ["Snapdragon 8 Gen 3", "200 МП", "S Pen", "AI функции"],
  },
  {
    id: 4,
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    storage: "128 ГБ",
    color: "Фиолетовый",
    price: 329000,
    condition: "new",
    badge: null,
    emoji: "📱",
    specs: ["Exynos 2400", "50 МП", "120 Гц", "IP68"],
  },
  {
    id: 5,
    name: "Xiaomi 14 Pro",
    brand: "Xiaomi",
    storage: "256 ГБ",
    color: "Белый",
    price: 389000,
    condition: "new",
    badge: "Выгодно",
    emoji: "📱",
    specs: ["Snapdragon 8 Gen 3", "Leica 50 МП", "90W зарядка", "AMOLED"],
  },
  {
    id: 6,
    name: "Xiaomi Redmi Note 13 Pro",
    brand: "Xiaomi",
    storage: "256 ГБ",
    color: "Зелёный",
    price: 169000,
    condition: "new",
    badge: null,
    emoji: "📱",
    specs: ["Helio G99", "200 МП", "67W зарядка", "5000 мАч"],
  },
  // USED PHONES
  {
    id: 7,
    name: "iPhone 13 Pro",
    brand: "Apple",
    storage: "256 ГБ",
    color: "Тёмная ночь",
    price: 269000,
    oldPrice: 420000,
    condition: "used",
    grade: "Отличное (A)",
    badge: "Б/У",
    emoji: "📱",
    specs: ["A15 Bionic", "ProMotion 120 Гц", "Тройная камера"],
  },
  {
    id: 8,
    name: "iPhone 12",
    brand: "Apple",
    storage: "128 ГБ",
    color: "Синий",
    price: 169000,
    oldPrice: 290000,
    condition: "used",
    grade: "Хорошее (B)",
    badge: "Б/У",
    emoji: "📱",
    specs: ["A14 Bionic", "5G", "Face ID", "Dual камера"],
  },
  {
    id: 9,
    name: "Samsung Galaxy S22",
    brand: "Samsung",
    storage: "128 ГБ",
    color: "Белый",
    price: 189000,
    oldPrice: 350000,
    condition: "used",
    grade: "Отличное (A)",
    badge: "Б/У",
    emoji: "📱",
    specs: ["Snapdragon 8 Gen 1", "50 МП", "4K видео", "IP68"],
  },
  {
    id: 10,
    name: "Samsung Galaxy A54",
    brand: "Samsung",
    storage: "128 ГБ",
    color: "Чёрный",
    price: 129000,
    oldPrice: 220000,
    condition: "used",
    grade: "Хорошее (B)",
    badge: "Б/У",
    emoji: "📱",
    specs: ["Exynos 1380", "50 МП", "5000 мАч", "Super AMOLED"],
  },
  {
    id: 11,
    name: "Xiaomi Redmi Note 11",
    brand: "Xiaomi",
    storage: "128 ГБ",
    color: "Серый",
    price: 79000,
    oldPrice: 120000,
    condition: "used",
    grade: "Хорошее (B)",
    badge: "Б/У",
    emoji: "📱",
    specs: ["Snapdragon 680", "50 МП", "5000 мАч", "90 Гц"],
  },
  {
    id: 12,
    name: "Google Pixel 7a",
    brand: "Google",
    storage: "128 ГБ",
    color: "Уголь",
    price: 219000,
    oldPrice: 320000,
    condition: "used",
    grade: "Отличное (A)",
    badge: "Б/У",
    emoji: "📱",
    specs: ["Google Tensor G2", "64 МП", "5G", "IP67"],
  },
];

const VISIBLE_COUNT = 8;
